default:
    extensions:
        Behat\Symfony2Extension\Extension:
            mink_driver: true
        Behat\MinkExtension\Extension:
            default_session: 'symfony2'
        symfony2_extension.phar:
            mink_driver: true
        mink_extension.phar:
            default_session: 'symfony2'