<?php

namespace LFSM\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExcelFileImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcelFileImportRepository extends EntityRepository
{
    
}
