<?php

namespace LFSM\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionRepository extends EntityRepository {

    public function myFindAllQuery()
    {
        $queryBuilder = $this->createQueryBuilder('q')
                ->orderBy('q.fct_lib');

        $query = $queryBuilder->getQuery();

        return $query;
    }

}
