<?php

namespace LFSM\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeRepository extends EntityRepository
{
    public function myFindAllQuery()
    {
        $queryBuilder = $this->createQueryBuilder('q')
                ->orderBy('q.name');

        $query = $queryBuilder->getQuery();

        return $query;
    }
}
