<?php

namespace LFSM\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RefProvenanceFichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefProvenanceFichierRepository extends EntityRepository {

    public function myFindAllQuery()
    {
        $queryBuilder = $this->createQueryBuilder('q')
                ->orderBy('q.prov_lib');

        $query = $queryBuilder->getQuery();

        return $query;
    }

}
