<?php

namespace LFSM\DonateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DateMontantFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateMontantFilterRepository extends EntityRepository
{
}
