<?php

namespace LFSM\DonateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DonateurFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonateurFilterRepository extends EntityRepository {

}
