<?php

namespace LFSM\DonateurBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * NoteDonateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteDonateurRepository extends EntityRepository
{
    public function getNotesByDonateur($donateur)
    {
        $queryBuilder = $this->createQueryBuilder('d')
                ->leftJoin('d.donateur', 'don')
                ->addSelect('don')
                ->andWhere('d.donateur=:donateur')
                ->setParameter('donateur', $donateur)
                ->orderBy('d.date', 'ASC');

        $results = $queryBuilder->getQuery()->getResult(Query::HYDRATE_OBJECT);

        return $results;
    }
}
